### ISSUE TITLE
Input value in webview gets lost after rotation

### ISSUE THREAD

**Issue by geniuslittleteddy** [billthefarmer/crossword#4]
Say if I open a webview and inputs username and password, their values get lost after screen orientation changes.

![Screen Shot 2020-08-05 at 10 38 25 PM](https://user-images.githubusercontent.com/67744580/89427027-5b379d80-d76d-11ea-818d-c8afca379a00.png)
![Screen Shot 2020-08-05 at 10 38 33 PM](https://user-images.githubusercontent.com/67744580/89427037-5d99f780-d76d-11ea-9c79-5cf016f16600.png)

**Comment by billthefarmer** [comment]
The webview in this app is intended as a convenience for looking up words rather than having to use another app. It certainly isn't intended for use as a general purpose browser and certainly not for notorious data snarfing sites like Facebook etc. The app saves and restores the state using the API provided, so any failing is down to the webview, there's not a lot a developer can do about it other than not use it and direct the user to a browser app instead.
